version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: shareit_gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/share-it

  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: shareit_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=share-it
      - POSTGRES_USER=vlad
      - POSTGRES_PASSWORD=91735vladB!